export const machines = {
    "built in refrigerator" : "Built In Refrigerator",
    "side by side" : "Side By Side Refrigerator",
    "bi sxs fridge" : "Built In Side By Side Refrigerator",
    "bi sxs" : "Built In Side By Side Refrigerator",
    "cook top electric" : "Electric Cooktop",
    "cook top gas" : "Gas Cooktop",
    "dryer electric" : "Electric Dryer",
    "dryer gas" : "Gas Dryer",
    "freezer built in" : "Built In Freezer",
    "bi fz" : "Built In Freezer",
    "freezer chest" : "Freezer Chest",
    "chest fz" : "Freezer Chest",
    "freezer upright" : "Upright Freezer",
    "garbage disposal" : "Garbase Disposal",
    "ice machine stand alone" : "Stand Alone Ice Machine",
    "ice machine" : "Ice Machine",
    "microwave and oven same unit" : "Microwave And Oven Unit",
    "mw/oven combo" : "Microwave And Oven Unit",
    "mini freezer" : "Mini Freezer",
    "uc freezer" : "Mini Freezer",
    "mini fridge" : "Mini Refrigerator",
    "uc fridge" : "Mini Refrigerator",
    "oven double electric" : "Electric Double Oven",
    "dbl oven" : "Double Oven",
    "oven single electric" : "Electric Oven",
    "range electric" : "Electric Range",
    "range gas" : "Gas Range",
    "refrigerator freezer on bottom" : "Refrigerator Freezer On Bottom",
    "b/t fridge" : "Refrigerator Freezer On Bottom",
    "bi b/t fridge" : "Built In Refrigerator Freezer On Bottom",
    "refrigerator freezer on top" : "Refrigerator Freezer On Top",
    "t/b fridge" : "Refrigerator Freezer On Top",
    "refrigerator french door 3 or 4 door" : "French Door Refrigerator",
    "bi fd fridge" : "Built In French Door Refrigerator",
    "fd fridge" : "French Door Refrigerator",
    "refrigerator side by side" : "Side By Side Refrigerator",
    "sxs fridge" : "Side By Side Refrigerator",
    "refrigerator standalone fridge" : "Standalone Refrigerator",
    "bi fridge" : "Built In Refrigerator",
    "trash compactor" : "Trash Compactor",
    "vent hood" : "Vent Hood",
    "warming drawer" : "Warming Drawer",
    "washer and dryer same unit" : "Washer And Dryer Unit",
    "w/d combo unit" : "Washer And Dryer Unit",
    "washer front load" : "Front Load Washing Machine",
    "fl wm" : "Front Load Washing Machine",
    "washer top load" : "Top Load Washing Machine",
    "tl wm" : "Top Load Washing Machine",
    "wine cooler" : "Wine Cooler",
    " e cooktop" : "Electric Cooktop",
    "tl wm" : "Top Load Washing Machine",
    "bi sxs" : "Built in Side By Side Refrigerator",
    " t compactor" : "Trash Compactor",
    " g cooktop" : "Gas Cooktop",
    " e dryer" : "Electric Dryer",
    " g dryer" : "Gas Dryer",
    " s oven" : "Single Electric Oven",
    " e range" : "Electric Range",
    " g range" : "Gas Range",
    "builtinrefrigerator" : "Built In Refrigerator",
    "sidebyside" : "Side By Side Refrigerator",
    "bisxsfridge" : "Built In Side By Side Refrigerator",
    "cooktopelectric" : "Electric Cook Top",
    "cooktopgas" : "Gas Cook Top",
    "dryerelectric" : "Electric Dryer",
    "dryergas" : "Gas Dryer",
    "freezerbuiltin" : "Built In Freezer",
    "bifz" : "Built In Freezer",
    "freezerchest" : "Freezer Chest",
    "chestfz" : "Freezer Chest",
    "freezerupright" : "Upright Freezer",
    "garbagedisposal" : "Gabage Disposal",
    "icemachinestandalone" : "Stand Alone Ice Machine",
    "icemachine" : "Ice Machine",
    "microwaveandovensameunit" : "Microwave And Oven Unit",
    "mw/ovencombo" : "Microwave And Oven Unit",
    "minifreezer" : "Mini Freezer",
    "ucfreezer" : "Mini Freezer",
    "minifridge" : "Mini Refrigerator",
    "ucfridge" : "Mini Refrigerator",
    "ovendoubleelectric" : "Electrice Double Oven",
    "dbloven" : "Double Oven",
    "ovensingleelectric" : "Electric Single Oven",
    "rangeelectric" : "Electric Range",
    "erange" : "Electric Range",
    "grange" : "Gas Range",
    "rangegas" : "Gas Range",
    "refrigeratorfreezeronbottom" : "Refrigerator Freezer On Bottom",
    "b/tfridge" : "Refrigerator Freezer On Bottom",
    "refrigeratorfreezeronbottom" : "Refrigerator Freezer On Bottom",
    "bib/tfridge" : "Built In Refrigerator Freezer On Bottom",
    "refrigeratorfreezerontop" : "Refrigerator Freezer On Top",
    "t/bfridge" : "Refrigerator Freezer On Top",
    "refrigeratorfrenchdoor3or4door" : "French Door Refrigerator",
    "bifdfridge" : "Built In French Door Refrigerator",
    "refrigeratorfrenchdoor3or4door" : "French Door Refrigerator",
    "fdfridge" : "French Door Refrigerator",
    "refrigeratorsidebyside" : "Side By Side Refrigerator",
    "sxsfridge" : "Side By Side Refrigerator",
    "refrigeratorstandalonefridge" : "Standalone Refrigerator",
    "bifridge" : "Built In Refrigerator",
    "trashcompactor" : "Trash Compactor",
    "venthood" : "Vent Hood",
    "warmingdrawer" : "Warming Drawer",
    "washeranddryersameunit" : "Washer And Dryer Unit",
    "w/dcombounit" : "Washer And Dryer Unit",
    "washerfrontload" : "Front Load Washing Machine",
    "flwm" : "Front Load Washing Machine",
    "washertopload" : "Top Load Washing Machine",
    "tlwm" : "Top Load Washing Machine",
    "winecooler" : "Wine Cooler",
    "dw" : "Dishwasher",
    "ecooktop" : "Electric Cooktop",
    "tlwm" : "Top Load Washing Machine",
    "sxs": "Side By Side Refrigerator",
    "bisxs" : "Built In Refrigerator",
    "tcompactor" : "Trash Compactor",
    "gcooktop" : "Gas Cooktop",
    "dishwasher" : "Dishwasher",
    "downdraft" : "Downdraft",
    "edryer" : "Electric Dryer",
    "gdryer" : "Gas Dryer",
    "fz" : "Freezer",
    "disposal" : "Disposal",
    "kegerator" : "Kegerator",
    "microwave" : "Microwave",
    "mw" : "Microwave",
    "soven" : "Single Electric Oven",
    "pedestal" : "Pedestal",
    "erange" : "Electric Range",
    "grange" : "Gas Range",
    "built-in-refrigerator" : "Built In Refrigerator",
    "side-by-side" : "Side By Side Refrigerator",
    "bi-sxs-fridge" : "Built In Side By Side Refrigerator",
    "cook-top-electric" : "Electric Cook Top",
    "cook-top-gas" : "Gas Cook Top",
    "dryer-electric" : "Electric Dryer",
    "dryer-gas" : "Gas Dryer",
    "freezer-built-in" : "Built In Freezer",
    "bi-fz" : "Built In Freezer",
    "freezer-chest" : "Freezer Chest",
    "chest-fz" : "Freezer Chest",
    "freezer-upright" : "Upright Freezer",
    "garbage-disposal" : "Gabage Disposal",
    "ice-machine-stand-alone" : "Stand Alone Ice Machine",
    "ice-machine" : "Ice Machine",
    "microwave-and-oven-same-unit" : "Microwave And Oven Unit",
    "mw/oven-combo" : "Microwave And Oven Unit",
    "mini-freezer" : "Mini Freezer",
    "uc-freezer" : "Mini Freezer",
    "mini-fridge" : "Mini Refrigerator",
    "uc-fridge" : "Mini Refrigerator",
    "oven-double-electric" : "Electrice Double Oven",
    "dbl-oven" : "Double Oven",
    "oven-single-electric" : "Electric Single Oven",
    "range-electric" : "Electric Range",
    "e-range" : "Electric Range",
    "g-range" : "Gas Range",
    "range-gas" : "Gas Range",
    "refrigerator-freezer-on-bottom" : "Refrigerator Freezer On Bottom",
    "b/t-fridge" : "Refrigerator Freezer On Bottom",
    "refrigerator-freezer-on-bottom" : "Refrigerator Freezer On Bottom",
    "bi-b/t-fridge" : "Built In Refrigerator Freezer On Bottom",
    "refrigerator-freezer-on-top" : "Refrigerator Freezer On Top",
    "t/b-fridge" : "Refrigerator Freezer On Top",
    "refrigerator-french-door-3-or-4-door" : "French Door Refrigerator",
    "bi-fd-fridge" : "Built In French Door Refrigerator",
    "refrigerator-french-door-3-or-4-door" : "French Door Refrigerator",
    "fd-fridge" : "French Door Refrigerator",
    "refrigerator-side-by-side" : "Side By Side Refrigerator",
    "sxs-fridge" : "Side By Side Refrigerator",
    "refrigerator-standalone-fridge" : "Standalone Refrigerator",
    "bi-fridge" : "Built In Refrigerator",
    "trash-compactor" : "Trash Compactor",
    "vent-hood" : "Vent Hood",
    "warming-drawer" : "Warming Drawer",
    "washer-and-dryer-same-unit" : "Washer And Dryer Unit",
    "w/d-combo-unit" : "Washer And Dryer Unit",
    "washer-front-load" : "Front Load Washing Machine",
    "fl-wm" : "Front Load Washing Machine",
    "washer-top-load" : "Top Load Washing Machine",
    "tl-wm" : "Top Load Washing Machine",
    "wine-cooler" : "Wine Cooler",
    "e-cooktop" : "Electric Cooktop",
    "tl-wm" : "Top Load Washing Machine",
    "bi-sxs" : "Built In Refrigerator",
    "t-compactor" : "Trash Compactor",
    "g-cooktop" : "Gas Cooktop",
    "e-dryer" : "Electric Dryer",
    "g-dryer" : "Gas Dryer",
    "s-oven" : "Single Electric Oven",
    "pedestal" : "Pedestal",
    "e-range" : "Electric Range",
    "g-range" : "Gas Range",
    "cooktop": "Gas Cooktop",
    "gas cooktop": "Gas Cooktop",
    "electric cooktop": "Electric Cooktop"
}
export const manufactors = {
    "amana": "Amana",
    "bosch": "Bosch",
    "bsh": "Bosch",
    "crosley": "Crosley",
    "electrolux": "Electrolux",
    "el": "Electrolux",
    "5-star": "5 Star",
    "5star": "5 Star",
    "frigidair": "Frigidaire",
    "fr": "Frigidaire",
    "ge": "General Electric",
    "general-electric": "General Electric",
    "ikea": "Ikea",
    "hoshizaki": "Hoshizaki",
    "hosh": "Hoskizaki",
    "hotpoint": "Hotpoint",
    "hot-point": "Hotpoint",
    "inglis": 'WhirlPool',
    "insinkerator": "Insink",
    "insink": "Insink",
    "jenn-air": "Jenn Air",
    "jennair": "Jenn Air",
    "JA": "Jenn Air",
    "kenmore": "Kenmore",
    "ken-more": "Kenmore",
    "km": "Kenmore",
    "kirkland": "Whirlpool",
    "kirk-land": "Whirlpool",
    "kitchen-aid": "Kitchen Aid",
    "ka": "Kitchen Aid",
    "kitchenaid": "Kitchen Aid",
    "lg": "Lifes Good",
    "lifes-good": "Lifes Good",
    "magic-chef": "Magic Chef",
    "mc": "Magic Chef",
    "maytag": "Maytag",
    "mtg": "Maytag",
    "miele": "Miele",
    "panasonic": "Panasonic",
    "pan": "Panasonic",
    "pana-sonic": "Panasonic",
    "roper": "Whirlpool",
    "samsung": "Samsung",
    "sam": "Samsung",
    "speed-queen": "Speed Queen",
    "sq": "Speed Queen",
    "speedqueen": "Speed Queen",
    "sub-zero": "Sub Zero",
    "subzero": "Sub Zero",
    "sz": "Sub Zero",
    "uline": "U-Line",
    "u-line": "U-Line",
    "viking": "Viking",
    "whirlpool": "Whirlpool",
    "wp": "Whirlpool",
    "whilr-pool": "Whirlpool",
    "wolf": "Wolf",
    "magic chef": "Magic Chef",
    "speed queen": "Speed Queen",
    "sub zero": "Sub Zero",
    "kitchen aid": "Kitchen Aid",
    "general electric": "General Electric",
    "u line": "U Line"
}
