export const machine_types = {
    "refrigerator" : "Refrigerator",
    "fridge" : "Refrigerator",
    "fz" : "Freezer",
    "freezer" : "Freezer",
    "freezer chest" : "Freezer Chest",
    "chest fz" : "Freezer Chest",
    "cook top" : "Cooktop",
    "cooktop" : "Cooktop",
    "stovetop": "StoveTop",
    "stove top": "StoveTop",
    "range" : "Range",
    "mw/oven" : "Microwave And Oven Unit",
    "oven" : "Oven",
    "microwave and oven same unit" : "Microwave And Oven Unit",
    "mw": "Microwave",
    "microwave": "Microwave",
    "garbage disposal" : "Garbase Disposal",
    "ice machine" : "Ice Machine",
    "trash compactor" : "Trash Compactor",
    "vent hood" : "Vent Hood",
    "warming drawer" : "Warming Drawer",
    "dishwasher": "Dishwasher",
    "dw": "Dishwasher",
    "washer" : "Washing Machine",
    "dryer" : "Dryer",
    "washer and dryer same unit" : "Washer And Dryer Unit",
    "w/d combo unit" : "Washer And Dryer Unit",
    "wm" : "Washing Machine",
    "wine cooler" : "Wine Cooler",
    "disposal" : "Disposal",
    "kegerator" : "Kegerator",
    "pedestal" : "Pedestal"
}

export const machine_formats = {
        "built-in": "Built In",
        "side-by-side": "Side By Side",
        "gas": "Gas",
        "electric": "Electric",
        "double": "Double",
        "combo": "Combo",
        "mini": "Mini",
        "bottom/top": "Freezer On Bottom",
        "top/bottom": "Freezer On Top",
        "g": "Gas",
        "g-": "Gas",
        "e ": "Electric",
        "e-": "Electric",
        "dbl": "Double",
        "bi": "Built In",
        "bi-": "Built In",
        "built in": "Built In",
        "sxs": "Side By Side",
        "side by side": "Side By Side",
        "uc": "Mini",
        "uc-": "Mini",
        "b/t": "Freezer On Bottom",
        "b/t-": "Freezer On Bottom",
        "t/b": "Freezer On Top",
        "t/b-": "Freezer On Top",
        "fd": "French Door",
        "fd-": "French Door",
        "french door": "French Door",
        "fl": "Front Loading",
        "fl-": "Front Loading",
        "front load": "Front Loading",
        "tl": "Top Loading",
        "tl-": "Top Loading",
        "top load": "Top Loading"
}
export const manufacturers = {
    "amana": "Amana",
    "bosch": "Bosch",
    "bsh": "Bosch",
    "crosley": "Crosley",
    "electrolux": "Electrolux",
    "el": "Electrolux",
    "5-star": "5 Star",
    "5star": "5 Star",
    "frigidair": "Frigidaire",
    "fr": "Frigidaire",
    "ge": "General Electric",
    "general-electric": "General Electric",
    "ikea": "Ikea",
    "hoshizaki": "Hoshizaki",
    "hosh": "Hoskizaki",
    "hotpoint": "Hotpoint",
    "hot-point": "Hotpoint",
    "inglis": 'WhirlPool',
    "insinkerator": "Insink",
    "insink": "Insink",
    "jenn-air": "Jenn Air",
    "jennair": "Jenn Air",
    "ja": "Jenn Air",
    "kenmore": "Kenmore",
    "ken-more": "Kenmore",
    "km": "Kenmore",
    "kirkland": "Whirlpool",
    "kirk-land": "Whirlpool",
    "kitchen-aid": "Kitchen Aid",
    "ka": "Kitchen Aid",
    "kitchenaid": "Kitchen Aid",
    "lg": "Lifes Good",
    "lifes-good": "Lifes Good",
    "magic-chef": "Magic Chef",
    "mc": "Magic Chef",
    "maytag": "Maytag",
    "mtg": "Maytag",
    "miele": "Miele",
    "panasonic": "Panasonic",
    "pan": "Panasonic",
    "pana-sonic": "Panasonic",
    "roper": "Whirlpool",
    "samsung": "Samsung",
    "sam": "Samsung",
    "speed-queen": "Speed Queen",
    "sq": "Speed Queen",
    "speedqueen": "Speed Queen",
    "sub-zero": "Sub Zero",
    "subzero": "Sub Zero",
    "sz": "Sub Zero",
    "uline": "U-Line",
    "u-line": "U-Line",
    "viking": "Viking",
    "whirlpool": "Whirlpool",
    "wp": "Whirlpool",
    "whilr-pool": "Whirlpool",
    "wolf": "Wolf",
    "magic chef": "Magic Chef",
    "speed queen": "Speed Queen",
    "sub zero": "Sub Zero",
    "kitchen aid": "Kitchen Aid",
    "general electric": "General Electric",
    "u line": "U Line"
}
